/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// BucketServiceAddBucketTagsRequest struct for BucketServiceAddBucketTagsRequest
type BucketServiceAddBucketTagsRequest struct {
	// Tags - list of tags set for the Bucket
	Tag []BucketServiceCreateBucketRequestTagInner `json:"Tag,omitempty"`
	// Namespace associated with the user/tenant that is allowed to access the bucket
	Namespace *string `json:"namespace,omitempty"`
}
