/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// BucketServiceSetBucketHeadMetadataRequest struct for BucketServiceSetBucketHeadMetadataRequest
type BucketServiceSetBucketHeadMetadataRequest struct {
	// The head-type of the bucket metadata (S3, SWIFT, ATMOS, HDFS, CAS, NFS, INTERNAL, DT_QUERY)
	HeadType *string `json:"head_type,omitempty"`
	// Bucket Head Metadata entry
	Metadata []BucketServiceSetBucketHeadMetadataRequestMetadataInner `json:"metadata,omitempty"`
	// Namespace of the bucket
	Namespace *string `json:"namespace,omitempty"`
}
