/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// BucketServiceCreateBucketRequestCopyPolicy struct for BucketServiceCreateBucketRequestCopyPolicy
type BucketServiceCreateBucketRequestCopyPolicy struct {
	DaysAfterLastWrite    *int64  `json:"days_after_last_write,omitempty"`
	MinimumSize           *int64  `json:"minimum_size,omitempty"`
	ExternalEndpoint      *string `json:"external_endpoint,omitempty"`
	TargetRegion          *string `json:"target_region,omitempty"`
	TargetBucket          *string `json:"target_bucket,omitempty"`
	TargetAccessKey       *string `json:"target_access_key,omitempty"`
	TargetSecretKey       *string `json:"target_secret_key,omitempty"`
	TargetAccount         *string `json:"target_account,omitempty"`
	TargetRole            *string `json:"target_role,omitempty"`
	TagFilter             *string `json:"tag_filter,omitempty"`
	PolicyType            *string `json:"policy_type,omitempty"`
	BackupReadTarget      *bool   `json:"backup_read_target,omitempty"`
	SseS3Enabled          *bool   `json:"sse_s3_enabled,omitempty"`
	DetailedLogEnabled    *bool   `json:"detailed_log_enabled,omitempty"`
	DetailedLogErrorsOnly *bool   `json:"detailed_log_errors_only,omitempty"`
	DetailedLogBucket     *string `json:"detailed_log_bucket,omitempty"`
	DetailedLogPrefix     *string `json:"detailed_log_prefix,omitempty"`
	ExternalCerts         *string `json:"external_certs,omitempty"`
}
