/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// BucketServicePutBucketDefaultLockConfigurationRequestRuleDefaultRetention The default retention period that you want to apply to new objects placed in  the specified bucket.
type BucketServicePutBucketDefaultLockConfigurationRequestRuleDefaultRetention struct {
	// The default Object Lock retention mode you want to apply to new objects  placed in the specified bucket.
	Mode *string `json:"Mode,omitempty"`
	// The number of years that you want to specify for the default retention  period. Either Days or Years must be specified, but not both.
	Years *int32 `json:"Years,omitempty"`
	// The number of days that you want to specify for the default retention period.  Either Days or Years must be specified, but not both.
	Days *int32 `json:"Days,omitempty"`
}
