/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// BucketServiceGetBucketQuotaResponse struct for BucketServiceGetBucketQuotaResponse
type BucketServiceGetBucketQuotaResponse struct {
	// Bucket name
	Bucketname *string `json:"bucketname,omitempty"`
	// Namespace name
	Namespace *string `json:"namespace,omitempty"`
	// Block size in GB. -1 indicates quota value not defined.
	BlockSize *int64 `json:"blockSize,omitempty"`
	// Notification size in GB. -1 indicates quota value not defined.
	NotificationSize        *int64 `json:"notificationSize,omitempty"`
	BlockSizeInCount        *int64 `json:"blockSizeInCount,omitempty"`
	NotificationSizeInCount *int64 `json:"notificationSizeInCount,omitempty"`
}
