/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// BucketServiceUpdateBucketQuotaRequest struct for BucketServiceUpdateBucketQuotaRequest
type BucketServiceUpdateBucketQuotaRequest struct {
	// Block size in GB. Cannot be less than 1GB or use decimal values.  Can be set to -1 to indicate quota value not defined.
	BlockSize *int64 `json:"blockSize,omitempty"`
	// Notification size in GB. Cannot be less than 1GB or use decimal values.  Can be set to -1 to indicate quota value not defined.
	NotificationSize *int64 `json:"notificationSize,omitempty"`
	// Namespace to which this bucket belongs
	Namespace               *string `json:"namespace,omitempty"`
	BlockSizeInCount        *int64  `json:"blockSizeInCount,omitempty"`
	NotificationSizeInCount *int64  `json:"notificationSizeInCount,omitempty"`
}
