/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// List Groups For User pagination helper methods
func (a *IamServiceListGroupsForUserResponse) GetNextMarker() *string {
	return a.ListGroupsForUserResult.Marker
}

func (o *IamServiceListGroupsForUserResponse) GetPaginatedResp() []IamServiceListGroupsForUserResponseListGroupsForUserResultGroupsInner {
	return o.ListGroupsForUserResult.Groups
}

// List All Groups pagination helper methods
func (a *IamServiceListGroupsResponse) GetNextMarker() *string {
	return a.ListGroupsResult.Marker
}

func (o *IamServiceListGroupsResponse) GetPaginatedResp() []IamServiceListGroupsResponseListGroupsResultGroupsInner {
	return o.ListGroupsResult.Groups
}

// List All Users pagination helper methods
func (a *IamServiceListUsersResponse) GetNextMarker() *string {
	return a.ListUsersResult.Marker
}

func (o *IamServiceListUsersResponse) GetPaginatedResp() []IamServiceListUsersResponseListUsersResultUsersInner {
	return o.ListUsersResult.Users
}

// List Users By Group pagination helper methods
func (a *IamServiceGetGroupResponse) GetNextMarker() *string {
	return a.GetGroupResult.Marker
}

func (o *IamServiceGetGroupResponse) GetPaginatedResp() []IamServiceGetGroupResponseGetGroupResultUsersInner {
	return o.GetGroupResult.Users
}

func (a *IamServiceListRolesResponse) GetNextMarker() *string {
	return a.ListRolesResult.Marker
}

func (o *IamServiceListRolesResponse) GetPaginatedResp() []IamRole {
	return o.ListRolesResult.Roles
}
