/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// BucketServiceGetPermissionsResponsePermissionInner struct for BucketServiceGetPermissionsResponsePermissionInner
type BucketServiceGetPermissionsResponsePermissionInner struct {
	// Permission id
	Id *string `json:"id,omitempty"`
	// Display name
	DisplayName *string `json:"display_name,omitempty"`
	// Description
	Description *string `json:"description,omitempty"`
}
