/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// IamPolicyAttached struct for IamPolicyAttached
type IamPolicyAttached struct {
	// The resource name of the policy.
	PolicyArn *string `json:"PolicyArn,omitempty"`
	// The friendly name of the policy.
	PolicyName *string `json:"PolicyName,omitempty"`
}
