/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// MgmtUserInfoServiceCreateLocalUserInfoRequest struct for MgmtUserInfoServiceCreateLocalUserInfoRequest
type MgmtUserInfoServiceCreateLocalUserInfoRequest struct {
	// Management user id
	UserId string `json:"userId"`
	// Password for the management user
	Password *string `json:"password,omitempty"`
	// If set to true, assigns the  management user to the System Admin role
	IsSystemAdmin *bool `json:"isSystemAdmin,omitempty"`
	// If set to true, assigns the management user to the System Monitor role
	IsSystemMonitor *bool `json:"isSystemMonitor,omitempty"`
	// If set to true, assigns the management user to the Security Admin role
	IsSecurityAdmin *bool `json:"isSecurityAdmin,omitempty"`
	// If set to true, its a domain.
	IsExternalGroup *bool `json:"is_external_group,omitempty"`
}
