/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// BucketServiceGetBucketVersioningResponse struct for BucketServiceGetBucketVersioningResponse
type BucketServiceGetBucketVersioningResponse struct {
	// Versioning state of the bucket
	Status *string `json:"Status,omitempty"`
}
