/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// BucketServiceCreateBucketRequestMinMaxGovernor Retention Min Max Governor
type BucketServiceCreateBucketRequestMinMaxGovernor struct {
	EnforceRetention         *bool  `json:"enforce_retention,omitempty"`
	MinimumFixedRetention    *int64 `json:"minimum_fixed_retention,omitempty"`
	MaximumFixedRetention    *int64 `json:"maximum_fixed_retention,omitempty"`
	MinimumVariableRetention *int64 `json:"minimum_variable_retention,omitempty"`
	MaximumVariableRetention *int64 `json:"maximum_variable_retention,omitempty"`
}
