/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// BucketServiceUpdateBucketOwnerRequest struct for BucketServiceUpdateBucketOwnerRequest
type BucketServiceUpdateBucketOwnerRequest struct {
	// Namespace that is allowed to access this bucket
	Namespace string `json:"namespace"`
	// New owner of the bucket
	NewOwner string `json:"new_owner"`
	// flag indicating if previous bucket owner list is to be reset
	ResetPreviousOwners *bool `json:"reset_previous_owners,omitempty"`
}
