/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// UserSecretKeyServiceCreateNewKeyForUserResponse struct for UserSecretKeyServiceCreateNewKeyForUserResponse
type UserSecretKeyServiceCreateNewKeyForUserResponse struct {
	// Secret key
	SecretKey *string `json:"secret_key,omitempty"`
	// Secret key creation timestamp in ISO-8601 format
	KeyTimestamp *string `json:"key_timestamp,omitempty"`
	// Secret key expiry timestamp in ISO-8601 format
	KeyExpiryTimestamp *string                                   `json:"key_expiry_timestamp,omitempty"`
	Link               *UserManagementServiceAddUserResponseLink `json:"link,omitempty"`
	// SHA-256 hash of Secret key
	SecretKeyId *string `json:"secret_key_id,omitempty"`
}
