/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// IamPolicy Get policy
type IamPolicy struct {
	// The resource name of the policy.
	Arn *string `json:"Arn,omitempty"`
	// The number of entities (users, groups, and roles) that the policy is attached to.
	AttachmentCount *int32 `json:"AttachmentCount,omitempty"`
	// The date and time, in ISO 8601 date-time format, when the policy was created.
	CreateDate *string `json:"CreateDate,omitempty"`
	// The identifier for the version of the policy that is set as the default version.
	DefaultVersionId *string `json:"DefaultVersionId,omitempty"`
	// A friendly description of the policy.
	Description *string `json:"Description,omitempty"`
	// Specifies whether the policy can be attached to user, group, or role.
	IsAttachable *bool `json:"IsAttachable,omitempty"`
	// The path to the policy
	Path *string `json:"Path,omitempty"`
	// Resource name of the policy that is used to set permissions boundary for the policy.
	PermissionsBoundaryUsageCount *int32 `json:"PermissionsBoundaryUsageCount,omitempty"`
	// The stable and unique string identifying the policy.
	PolicyId *string `json:"PolicyId,omitempty"`
	// The friendly name of the policy.
	PolicyName *string `json:"PolicyName,omitempty"`
	// The date and time, in ISO 8601 date-time format, when the policy was created.
	UpdateDate *string `json:"UpdateDate,omitempty"`
}
