/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// UserManagementServiceGetUserTagsWithNamespaceResponse struct for UserManagementServiceGetUserTagsWithNamespaceResponse
type UserManagementServiceGetUserTagsWithNamespaceResponse struct {
	// User name
	UserName *string `json:"user_name,omitempty"`
	// Gets the tags associated with this user. Required.
	Tags []UserManagementServiceAddUserRequestTagsInner `json:"tags,omitempty"`
}
