/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// IamServiceListPoliciesResponse struct for IamServiceListPoliciesResponse
type IamServiceListPoliciesResponse struct {
	ListPoliciesResult *IamServiceListPoliciesResponseListPoliciesResult `json:"ListPoliciesResult,omitempty"`
	ResponseMetadata   *IamResponseMetadata                              `json:"ResponseMetadata,omitempty"`
}
