/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// List Groups For User pagination helper methods
func (a *IamServiceListGroupsForUserResponse) GetNextMarker() *string {
	return a.ListGroupsForUserResult.Marker
}

func (o *IamServiceListGroupsForUserResponse) GetPaginatedResp() []IamServiceListGroupsForUserResponseListGroupsForUserResultGroupsInner {
	return o.ListGroupsForUserResult.Groups
}

// List All Groups pagination helper methods
func (a *IamServiceListGroupsResponse) GetNextMarker() *string {
	return a.ListGroupsResult.Marker
}

func (o *IamServiceListGroupsResponse) GetPaginatedResp() []IamServiceListGroupsResponseListGroupsResultGroupsInner {
	return o.ListGroupsResult.Groups
}

// List All Users pagination helper methods
func (a *IamServiceListUsersResponse) GetNextMarker() *string {
	return a.ListUsersResult.Marker
}

func (o *IamServiceListUsersResponse) GetPaginatedResp() []IamServiceListUsersResponseListUsersResultUsersInner {
	return o.ListUsersResult.Users
}

// List Users By Group pagination helper methods
func (a *IamServiceGetGroupResponse) GetNextMarker() *string {
	return a.GetGroupResult.Marker
}

func (o *IamServiceGetGroupResponse) GetPaginatedResp() []IamServiceGetGroupResponseGetGroupResultUsersInner {
	return o.GetGroupResult.Users
}

// List Policies pagination helper methods
func (a *IamServiceListPoliciesResponse) GetNextMarker() *string {
	return a.ListPoliciesResult.Marker
}

func (o *IamServiceListPoliciesResponse) GetPaginatedResp() []IamServiceGetPolicyResponseGetPolicyResultPolicy {
	return o.ListPoliciesResult.Policies
}

// List Attached User Policies pagination helper methods
func (a *IamServiceListAttachedUserPoliciesResponse) GetNextMarker() *string {
	return a.ListAttachedUserPoliciesResult.Marker
}

func (o *IamServiceListAttachedUserPoliciesResponse) GetPaginatedResp() []IamServiceGetPolicyResponseGetPolicyResultPolicy {
	return o.ListAttachedUserPoliciesResult.AttachedPolicies
}

// List Attached Group Policies pagination helper methods
func (a *IamServiceListAttachedGroupPoliciesResponse) GetNextMarker() *string {
	return a.ListAttachedGroupPoliciesResult.Marker
}

func (o *IamServiceListAttachedGroupPoliciesResponse) GetPaginatedResp() []IamServiceGetPolicyResponseGetPolicyResultPolicy {
	return o.ListAttachedGroupPoliciesResult.AttachedPolicies
}

// List Attached Role Policies pagination helper methods
func (a *IamServiceListAttachedRolePoliciesResponse) GetNextMarker() *string {
	return a.ListAttachedRolePoliciesResult.Marker
}

func (o *IamServiceListAttachedRolePoliciesResponse) GetPaginatedResp() []IamServiceGetPolicyResponseGetPolicyResultPolicy {
	return o.ListAttachedRolePoliciesResult.AttachedPolicies
}

