/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// IamServiceListGroupsForUserResponse struct for IamServiceListGroupsForUserResponse
type IamServiceListGroupsForUserResponse struct {
	ListGroupsForUserResult *IamServiceListGroupsForUserResponseListGroupsForUserResult `json:"ListGroupsForUserResult,omitempty"`
	ResponseMetadata        *IamServiceGetGroupResponseResponseMetadata                 `json:"ResponseMetadata,omitempty"`
}
