/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// Vdc struct for Vdc
type Vdc struct {
	// VDC id
	VdcId *string `json:"vdcId,omitempty"`
	// VDC name
	VdcName *string `json:"vdcName,omitempty"`
	// VDC end points
	InterVdcEndPoints *string `json:"interVdcEndPoints,omitempty"`
	// VDC cmd end points
	InterVdcCmdEndPoints *string `json:"interVdcCmdEndPoints,omitempty"`
	// Secret key for this VDC
	SecretKeys *string `json:"secretKeys,omitempty"`
	// True of vdc is permanently failed, false otherwise.
	PermanentlyFailed *bool `json:"permanentlyFailed,omitempty"`
	// True of this vdc is local, false otherwise
	Local *bool `json:"local,omitempty"`
	// True of this vdc is enabled for encryption, false otherwise
	IsEncryptionEnabled *bool `json:"is_encryption_enabled,omitempty"`
	// The management end points for the VDC
	ManagementEndPoints *string `json:"managementEndPoints,omitempty"`
	Hosted              *bool   `json:"hosted,omitempty"`
	// Name assigned to this resource in ECS. The resource name is set by  a user and can be changed at any time. It is not a unique identifier.
	Name *string `json:"name,omitempty"`
	// Identifier that is generated by ECS when the resource is created.  The resource Id is guaranteed to be unique  and  immutable across all  virtual data centers for all time.
	Id   *string `json:"id,omitempty"`
	Link *Link   `json:"link,omitempty"`
	// Timestamp that shows when this resource was created in ECS
	CreationTime *int64 `json:"creation_time,omitempty"`
	// Indicates whether the resource is inactive. When a user removes  a resource, the resource is put in this state before  it is removed from the ECS database.
	Inactive *bool `json:"inactive,omitempty"`
	// Indicates whether the resource is global.
	Global *bool `json:"global,omitempty"`
	// Indicates whether the resource is remote.
	Remote *bool                                                   `json:"remote,omitempty"`
	Vdc    *NamespaceServiceGetNamespacesResponseNamespaceInnerVdc `json:"vdc,omitempty"`
	// Indicated whether the resource is an internal resource
	Internal *bool `json:"internal,omitempty"`
}
