/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// BucketServiceSetBucketACLRequestAcl Get ACL for the bucket
type BucketServiceSetBucketACLRequestAcl struct {
	// Owner name
	Owner *string `json:"owner,omitempty"`
	// Default group
	DefaultGroup *string                                           `json:"default_group,omitempty"`
	UserAcl      []BucketServiceSetBucketACLRequestAclUserAclInner `json:"user_acl,omitempty"`
	// List of Acl group
	GroupAcl []BucketServiceSetBucketACLRequestAclGroupAclInner `json:"group_acl,omitempty"`
	// List of custom group Acls
	CustomgroupAcl []BucketServiceSetBucketACLRequestAclCustomgroupAclInner `json:"customgroup_acl,omitempty"`
	// The default group's file permissions
	DefaultGroupFilePerms []string `json:"default_group_file_perms,omitempty"`
	// The default group's directory permissions
	DefaultGroupDirPerms []string `json:"default_group_dir_perms,omitempty"`
}
