/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// BucketServiceGetBucketLockResponse struct for BucketServiceGetBucketLockResponse
type BucketServiceGetBucketLockResponse struct {
	// Bucket name to be locked.
	BucketName *string `json:"bucket_name,omitempty"`
	// Set to \"true\" for lock bucket and \"false\" for unlock bucket.
	IsLocked *bool `json:"isLocked,omitempty"`
}
