/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// ObjectVarrayServiceUpdateVirtualArrayRequest struct for ObjectVarrayServiceUpdateVirtualArrayRequest
type ObjectVarrayServiceUpdateVirtualArrayRequest struct {
	// Name of virtual array to be updated
	Name string `json:"name"`
	// Set true if varray is protected, false otherwise
	IsProtected bool `json:"isProtected"`
	// Description. If no description found, then \"Virtual Array\" is used by default
	Description *string `json:"description,omitempty"`
	// Is ColdStorage enabled on the virtual array
	IsColdStorageEnabled *bool `json:"isColdStorageEnabled,omitempty"`
	// Threshold percent at which warning alert is raised.  Valid values are from -1 to 100. Value of -1 means do not alert
	WarningAlertAt *int32 `json:"warningAlertAt,omitempty"`
	// Threshold percent at which error alert is raised.  Valid values are from -1 to 100. Value of -1 means do not alert
	ErrorAlertAt *int32 `json:"errorAlertAt,omitempty"`
	// Threshold percent at which critical alert is raised.  Valid values are from -1 to 100. Value of -1 means do not alert
	CriticalAlertAt *int32 `json:"criticalAlertAt,omitempty"`
	// Number of data blocks for configurable EC scheme
	NumberOfDataBlocks *int32 `json:"numberOfDataBlocks,omitempty"`
	// Number of code blocks for configurable EC scheme
	NumberOfCodeBlocks *int32 `json:"numberOfCodeBlocks,omitempty"`
	// Number of storage server instances for validation of configurable EC scheme
	NumberOfStorageServerInstances *int32 `json:"numberOfStorageServerInstances,omitempty"`
	// flag for status, -1 for null, 0 ~ 6 for value
	Status *int32 `json:"status,omitempty"`
}
