/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// UserManagementServiceGetUserInfoResponse struct for UserManagementServiceGetUserInfoResponse
type UserManagementServiceGetUserInfoResponse struct {
	// Namespace that owns the user
	Namespace string `json:"namespace"`
	// User name
	Name string `json:"name"`
	// Set true if user needs to be is to be locked, false otherwise
	Locked bool `json:"locked"`
	// Gets the user's creation date as an ISO-8601 timestamp.
	Created string `json:"created"`
	// Gets the tags associated with this user. May be null if the user has no  tags.
	Tag []UserManagementServiceAddUserRequestTagsInner `json:"tag,omitempty"`
	// Gets the user's centerapassword.
	Centerapassword string `json:"centerapassword"`
	// Gets the user's swiftpassword.
	Swiftpassword string `json:"swiftpassword"`
}
