/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// MgmtUserInfoServiceModifyLocalUserInfoRequest struct for MgmtUserInfoServiceModifyLocalUserInfoRequest
type MgmtUserInfoServiceModifyLocalUserInfoRequest struct {
	// Password for the management user
	Password *string `json:"password,omitempty"`
	// Assigns or removes management user to /from System Admin role.
	IsSystemAdmin *bool `json:"isSystemAdmin,omitempty"`
	// Assigns or removes management user to /from System Monitor role.
	IsSystemMonitor *bool `json:"isSystemMonitor,omitempty"`
	// Assigns or removes management user to/from Security Admin role.
	IsSecurityAdmin *bool `json:"isSecurityAdmin,omitempty"`
}
