/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// ZoneInfoServiceInsertVdcInfoRequest struct for ZoneInfoServiceInsertVdcInfoRequest
type ZoneInfoServiceInsertVdcInfoRequest struct {
	// Name of VDC to be inserted
	VdcName *string `json:"vdcName,omitempty"`
	// End points for the VDC
	InterVdcEndPoints *string `json:"interVdcEndPoints,omitempty"`
	// Control Plane end points for the VDC
	InterVdcCmdEndPoints *string `json:"interVdcCmdEndPoints,omitempty"`
	// Secret key to encrypt communication between VDC
	SecretKeys *string `json:"secretKeys,omitempty"`
	// The management end points for the VDC
	ManagementEndPoints *string `json:"managementEndPoints,omitempty"`
}
