/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// UserManagementServiceGetAllUsersResponseBlobuserInner struct for UserManagementServiceGetAllUsersResponseBlobuserInner
type UserManagementServiceGetAllUsersResponseBlobuserInner struct {
	// Userid of the user
	Userid string `json:"userid"`
	// Namespace associated with the corresponding user
	Namespace *string `json:"namespace,omitempty"`
}
