/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// UserManagementServiceSetUserLockRequest struct for UserManagementServiceSetUserLockRequest
type UserManagementServiceSetUserLockRequest struct {
	// User name to be locked/unlocked
	User string `json:"user"`
	// Namespace for this user
	Namespace *string `json:"namespace,omitempty"`
	// Set true if user needs to be is to be locked, false otherwise.
	IsLocked bool `json:"isLocked"`
}
