/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// IamServiceListAccessKeysResponse struct for IamServiceListAccessKeysResponse
type IamServiceListAccessKeysResponse struct {
	ListAccessKeysResult *IamServiceListAccessKeysResponseListAccessKeysResult `json:"ListAccessKeysResult,omitempty"`
	ResponseMetadata     *IamServiceGetGroupResponseResponseMetadata           `json:"ResponseMetadata,omitempty"`
}
