/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// UserManagementServiceAddUserRequestTagsInner struct for UserManagementServiceAddUserRequestTagsInner
type UserManagementServiceAddUserRequestTagsInner struct {
	// The name of a tag
	Name *string `json:"name,omitempty"`
	// The value of a tag
	Value *string `json:"value,omitempty"`
}
