/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// BucketServiceGetBucketsResponseObjectBucketInnerSearchMetadata Metadata keys associated with the bucket.
type BucketServiceGetBucketsResponseObjectBucketInnerSearchMetadata struct {
	// Getter for the metadata.
	Metadata []BucketServiceCreateBucketRequestMetadataInner `json:"metadata,omitempty"`
	// Getter for the enabled flag.
	IsEnabled *bool `json:"isEnabled,omitempty"`
	// Getter for the mdTokens flag.
	MdTokens *bool `json:"mdTokens,omitempty"`
	// Getter for maxKeys.
	MaxKeys *int32 `json:"maxKeys,omitempty"`
}
