/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// IamTagKeyValue struct for IamTagKeyValue
type IamTagKeyValue struct {
	// The name of the tag.
	Key *string `json:"key,omitempty"`
	// The value of the tag.
	Value *string `json:"value,omitempty"`
}
