/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// BucketServiceSetBucketACLRequestAclUserAclInner struct for BucketServiceSetBucketACLRequestAclUserAclInner
type BucketServiceSetBucketACLRequestAclUserAclInner struct {
	// User name
	User *string `json:"user,omitempty"`
	// Permission list
	Permission []string `json:"permission,omitempty"`
}
