/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// BucketServiceSetAdvancedMetadataSearchTargetRequest struct for BucketServiceSetAdvancedMetadataSearchTargetRequest
type BucketServiceSetAdvancedMetadataSearchTargetRequest struct {
	TargetName *string `json:"target_name,omitempty"`
	StreamName *string `json:"stream_name,omitempty"`
}
