/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// BucketServiceSetBucketDefaultGroupRequest struct for BucketServiceSetBucketDefaultGroupRequest
type BucketServiceSetBucketDefaultGroupRequest struct {
	// Flag indicating the Read permission for default group
	DefaultGroupFileReadPermission *bool `json:"default_group_file_read_permission,omitempty"`
	// Flag indicating the file write permission for default group
	DefaultGroupFileWritePermission *bool `json:"default_group_file_write_permission,omitempty"`
	// Flag indicating the file execute permission for default group
	DefaultGroupFileExecutePermission *bool `json:"default_group_file_execute_permission,omitempty"`
	// Flag indicating the directory read permission for default group. This is only applicable to folders created  within the Filesystem-Enabled bucket. It is not applicable to files/objects
	DefaultGroupDirReadPermission *bool `json:"default_group_dir_read_permission,omitempty"`
	// Flag indicating the directory write permission for default group. This is only applicable to folders created  within the Filesystem-Enabled bucket. It is not applicable to files/objects
	DefaultGroupDirWritePermission *bool `json:"default_group_dir_write_permission,omitempty"`
	// Flag indicating the directory execute permission for default group. This is only applicable to folders created  within the Filesystem-Enabled bucket. It is not applicable to files/objects
	DefaultGroupDirExecutePermission *bool `json:"default_group_dir_execute_permission,omitempty"`
	// Default group for Filesystem-enabled buckets
	DefaultGroup *string `json:"default_group,omitempty"`
	// Namespace for bucket
	Namespace *string `json:"namespace,omitempty"`
}
