/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// ServiceProvider struct for ServiceProvider
type ServiceProvider struct {
	// The base url of Service Provider for SAML ACS.
	Dns *string `json:"dns,omitempty"`
	// Used in the entity Id.
	Uuid *string `json:"uuid,omitempty"`
	// The unique identifier of the keystore.
	UniqueId *string `json:"unique_id,omitempty"`
	// The tag to be used for editing the service provider.
	Etag *string `json:"etag,omitempty"`
	// A repository of security keys and certificates.
	JavaKeystore *string `json:"java_keystore,omitempty"`
	// The unique alias used for accessing the keystore entry.
	KeyAlias *string `json:"key_alias,omitempty"`
	// The password used for accessing the keystore entry.
	KeyPassword *string `json:"key_password,omitempty"`
	// The date the provider was created.
	CreateTime *string `json:"create_time,omitempty"`
	// The date the provider was last modified.
	LastModified *string `json:"last_modified,omitempty"`
}
