/*
Dell ObjectScale/ECS Management API

Generated from ECS source code metadata. Provides reliable schemas and examples for client generation.

API version: 4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// BucketServiceGetBucketHeadMetadataResponse struct for BucketServiceGetBucketHeadMetadataResponse
type BucketServiceGetBucketHeadMetadataResponse struct {
	HeadType *string                                                  `json:"head_type,omitempty"`
	Metadata []BucketServiceSetBucketHeadMetadataRequestMetadataInner `json:"metadata,omitempty"`
}
