linters:
  default: none
  enable:
    - durationcheck
    - errcheck
    - forcetypeassert
    - godot
    - govet
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - unconvert
    - unparam
    - unused
  disable:
    - typecheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - internal/clientgen/
      - internal/client/
skip-dirs:
  - internal/clientgen
  - internal/client
  - internal/helper
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - internal/clientgen/
      - internal/client/
