/*
Copyright (c) 2025 Dell Inc., or its subsidiaries. All Rights Reserved.

Licensed under the Mozilla Public License Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://mozilla.org/MPL/2.0/


Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package models

import "github.com/hashicorp/terraform-plugin-framework/types"

type ReplicationGroupDatasourceModel struct {
	ID                types.String             `tfsdk:"id"`
	ReplicationGroups []ReplicationGroupEntity `tfsdk:"replication_groups"`
}

type ReplicationGroupEntity struct {
	// Description of the replication group
	Description types.String `tfsdk:"description"`

	// Name assigned to this resource in ECS. Not a unique identifier.
	Name types.String `tfsdk:"name"`

	// List of Varray mappings
	VarrayMappings []VarrayMapping `tfsdk:"varray_mappings"`

	// Parameter to check if rebalancing is enabled
	EnableRebalancing types.Bool `tfsdk:"enable_rebalancing"`

	// Parameter to check if the Vpool can access all namespaces
	IsAllowAllNamespaces types.Bool `tfsdk:"is_allow_all_namespaces"`

	// Parameter to check for full replication
	IsFullRep types.Bool `tfsdk:"is_full_rep"`

	// Parameter to check if replication target is used
	UseReplicationTarget types.Bool `tfsdk:"use_replication_target"`

	// Unique identifier generated by ECS
	Id types.String `tfsdk:"id"`

	// Timestamp when resource was created
	CreationTime types.Int64 `tfsdk:"creation_time"`

	// Indicates whether the resource is inactive
	Inactive types.Bool `tfsdk:"inactive"`

	// Indicates whether the resource is global
	Global types.Bool `tfsdk:"global"`

	// Indicates whether the resource is remote
	Remote types.Bool `tfsdk:"remote"`

	// VDC details
	Vdc VdcDetails `tfsdk:"vdc"`

	// Indicates whether the resource is internal
	Internal types.Bool `tfsdk:"internal"`
}

type VarrayMapping struct {
	// Virtual data center ID
	Name types.String `tfsdk:"name"`

	// Storage pool ID
	Value types.String `tfsdk:"value"`

	// Indicates if this is a replication target
	IsReplicationTarget types.Bool `tfsdk:"is_replication_target"`
}

type VdcDetails struct {
	// Virtual data center ID
	Id types.String `tfsdk:"id"`

	// Hyperlink to the VDC details
	Link VdcLink `tfsdk:"link"`
}

type VdcLink struct {
	Rel  types.String `tfsdk:"rel"`
	Href types.String `tfsdk:"href"`
}
