/*
Copyright (c) 2025 Dell Inc., or its subsidiaries. All Rights Reserved.

Licensed under the Mozilla Public License Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://mozilla.org/MPL/2.0/


Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package models

import "github.com/hashicorp/terraform-plugin-framework/types"

// VDC Ds Model.
type VDCDataSourceModel struct {
	// Filters (inputs)
	ID    types.String `tfsdk:"id"`
	Name  types.String `tfsdk:"name"`
	Local types.Bool   `tfsdk:"local"`

	// Results (computed)
	Vdcs []VdcDsItem `tfsdk:"vdcs"`
}

// VDC Ds Item tfsdk model.
type VdcDsItem struct {
	// VDC id
	VdcId types.String `tfsdk:"vdc_id"`
	// VDC name
	VdcName types.String `tfsdk:"vdc_name"`
	// VDC end points
	InterVdcEndPoints types.String `tfsdk:"inter_vdc_end_points"`
	// VDC cmd end points
	InterVdcCmdEndPoints types.String `tfsdk:"inter_vdc_cmd_end_points"`
	// Secret key for this VDC
	SecretKeys types.String `tfsdk:"secret_keys"`
	// True of vdc is permanently failed, false otherwise.
	PermanentlyFailed types.Bool `tfsdk:"permanently_failed"`
	// True of this vdc is local, false otherwise
	Local types.Bool `tfsdk:"local"`
	// True of this vdc is enabled for encryption, false otherwise
	IsEncryptionEnabled types.Bool `tfsdk:"is_encryption_enabled"`
	// The management end points for the VDC
	ManagementEndPoints types.String `tfsdk:"management_end_points"`
	Hosted              types.Bool   `tfsdk:"hosted"`
	// Name assigned to this resource in ECS. The resource name is set by  a user and can be changed at any time. It is not a unique identifier.
	Name types.String `tfsdk:"name"`
	// Identifier that is generated by ECS when the resource is created.  The resource Id is guaranteed to be unique  and  immutable across all  virtual data centers for all time.
	Id types.String `tfsdk:"id"`
	// Timestamp that shows when this resource was created in ECS
	CreationTime types.Int64 `tfsdk:"creation_time"`
	// Indicates whether the resource is inactive. When a user removes  a resource, the resource is put in this state before  it is removed from the ECS database.
	Inactive types.Bool `tfsdk:"inactive"`
	// Indicates whether the resource is global.
	Global types.Bool `tfsdk:"global"`
	// Indicates whether the resource is remote.
	Remote types.Bool `tfsdk:"remote"`
	// Indicated whether the resource is an internal resource
	Internal types.Bool `tfsdk:"internal"`
}
