package provider

import (
	"context"
	"fmt"
	"terraform-provider-objectscale/internal/client"
	"terraform-provider-objectscale/internal/clientgen"
	"terraform-provider-objectscale/internal/helper"
	"terraform-provider-objectscale/internal/models"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &BucketDataSource{}

func NewBucketDataSource() datasource.DataSource {
	return &BucketDataSource{}
}

type BucketDataSource struct {
	client *client.Client
}

func (d *BucketDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_bucket"
}

// Schema describes the data source arguments and results.
func (d *BucketDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Retrieve IAM Groups from ObjectScale IAM.",
		Description:         "Retrieve IAM Groups from ObjectScale IAM.",
		Attributes: map[string]schema.Attribute{

			"id": schema.StringAttribute{
				Description:         "Identifier",
				MarkdownDescription: "Identifier",
				Computed:            true,
			},

			"namespace": schema.StringAttribute{
				Description:         "Name of the namespace.",
				MarkdownDescription: "Name of the namespace.",
				Required:            true,
			},

			"bucket_name_prefix": schema.StringAttribute{
				Description:         "Prefix of the Bucket name.",
				MarkdownDescription: "Prefix of the Bucket name.",
				Optional:            true,
			},

			"buckets": schema.ListNestedAttribute{
				Description:         "List of Buckets",
				MarkdownDescription: "List of Buckets",
				Computed:            true,

				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{

						"name": schema.StringAttribute{
							Description:         "Name assigned to this bucket resource in ECS.",
							MarkdownDescription: "Name assigned to this bucket resource in ECS.",
							Computed:            true,
						},
						"id": schema.StringAttribute{
							Description:         "Unique identifier generated by ECS for the bucket.",
							MarkdownDescription: "Unique identifier generated by ECS for the bucket.",
							Computed:            true,
						},
						"created": schema.StringAttribute{
							Description:         "Bucket creation time.",
							MarkdownDescription: "Bucket creation time.",
							Computed:            true,
						},
						"softquota": schema.StringAttribute{
							Description:         "Bucket soft quota.",
							MarkdownDescription: "Bucket soft quota.",
							Computed:            true,
						},
						"fs_access_enabled": schema.BoolAttribute{
							Description:         "File system access enabled status.",
							MarkdownDescription: "File system access enabled status.",
							Computed:            true,
						},
						"locked": schema.BoolAttribute{
							Description:         "Locked status of the bucket.",
							MarkdownDescription: "Locked status of the bucket.",
							Computed:            true,
						},
						"vpool": schema.StringAttribute{
							Description:         "Replication group id.",
							MarkdownDescription: "Replication group id.",
							Computed:            true,
						},
						"namespace": schema.StringAttribute{
							Description:         "Namespace of the bucket.",
							MarkdownDescription: "Namespace of the bucket.",
							Computed:            true,
						},
						"owner": schema.StringAttribute{
							Description:         "Bucket owner.",
							MarkdownDescription: "Bucket owner.",
							Computed:            true,
						},
						"is_stale_allowed": schema.BoolAttribute{
							Description:         "IsStaleAllowed flag.",
							MarkdownDescription: "IsStaleAllowed flag.",
							Computed:            true,
						},
						"is_object_lock_with_ado_allowed": schema.BoolAttribute{
							Description:         "If true, Object Lock and ADO can be enabled together.",
							MarkdownDescription: "If true, Object Lock and ADO can be enabled together.",
							Computed:            true,
						},
						"is_tso_read_only": schema.BoolAttribute{
							Description:         "IsTsoReadOnly flag.",
							MarkdownDescription: "IsTsoReadOnly flag.",
							Computed:            true,
						},
						"is_object_lock_enabled": schema.BoolAttribute{
							Description:         "IsObjectLockEnabled flag.",
							MarkdownDescription: "IsObjectLockEnabled flag.",
							Computed:            true,
						},
						"default_object_lock_retention_mode": schema.StringAttribute{
							Description:         "Default object lock retention mode.",
							MarkdownDescription: "Default object lock retention mode.",
							Computed:            true,
						},
						"default_object_lock_retention_years": schema.Int64Attribute{
							Description:         "Default object lock retention years.",
							MarkdownDescription: "Default object lock retention years.",
							Computed:            true,
						},
						"default_object_lock_retention_days": schema.Int64Attribute{
							Description:         "Default object lock retention days.",
							MarkdownDescription: "Default object lock retention days.",
							Computed:            true,
						},
						"is_encryption_enabled": schema.StringAttribute{
							Description:         "D@RE Bucket isEncryptionEnabled flag.",
							MarkdownDescription: "D@RE Bucket isEncryptionEnabled flag.",
							Computed:            true,
						},
						"default_retention": schema.Int64Attribute{
							Description:         "Default bucket retention.",
							MarkdownDescription: "Default bucket retention.",
							Computed:            true,
						},
						"block_size": schema.Int64Attribute{
							Description:         "Block size in GB.",
							MarkdownDescription: "Block size in GB.",
							Computed:            true,
						},
						"auto_commit_period": schema.Int64Attribute{
							Description:         "Auto-commit interval.",
							MarkdownDescription: "Auto-commit interval.",
							Computed:            true,
						},
						"notification_size": schema.Int64Attribute{
							Description:         "Notification size in GB.",
							MarkdownDescription: "Notification size in GB.",
							Computed:            true,
						},
						"api_type": schema.StringAttribute{
							Description:         "API type.",
							MarkdownDescription: "API type.",
							Computed:            true,
						},
						"retention": schema.Int64Attribute{
							Description:         "Default retention value for the bucket.",
							MarkdownDescription: "Default retention value for the bucket.",
							Computed:            true,
						},
						"default_group_file_read_permission": schema.BoolAttribute{
							Description:         "Read permission for default group.",
							MarkdownDescription: "Read permission for default group.",
							Computed:            true,
						},
						"default_group_file_write_permission": schema.BoolAttribute{
							Description:         "File write permission for default group.",
							MarkdownDescription: "File write permission for default group.",
							Computed:            true,
						},
						"default_group_file_execute_permission": schema.BoolAttribute{
							Description:         "File execute permission for default group.",
							MarkdownDescription: "File execute permission for default group.",
							Computed:            true,
						},
						"default_group_dir_read_permission": schema.BoolAttribute{
							Description:         "Directory read permission for default group.",
							MarkdownDescription: "Directory read permission for default group.",
							Computed:            true,
						},
						"default_group_dir_write_permission": schema.BoolAttribute{
							Description:         "Directory write permission for default group.",
							MarkdownDescription: "Directory write permission for default group.",
							Computed:            true,
						},
						"default_group_dir_execute_permission": schema.BoolAttribute{
							Description:         "Directory execute permission for default group.",
							MarkdownDescription: "Directory execute permission for default group.",
							Computed:            true,
						},
						"default_group": schema.StringAttribute{
							Description:         "Bucket's default group.",
							MarkdownDescription: "Bucket's default group.",
							Computed:            true,
						},
						"audit_delete_expiration": schema.Int64Attribute{
							Description:         "Audit delete expiration in seconds.",
							MarkdownDescription: "Audit delete expiration in seconds.",
							Computed:            true,
						},
						"is_empty_bucket_in_progress": schema.BoolAttribute{
							Description:         "If true, the bucket is being deleted (read-only until operation completes).",
							MarkdownDescription: "If true, the bucket is being deleted (read-only until operation completes).",
							Computed:            true,
						},
						"block_size_in_count": schema.Int64Attribute{
							Description:         "Block size in count.",
							MarkdownDescription: "Block size in count.",
							Computed:            true,
						},
						"notification_size_in_count": schema.Int64Attribute{
							Description:         "Notification size in count.",
							MarkdownDescription: "Notification size in count.",
							Computed:            true,
						},
						"enable_advanced_metadata_search": schema.BoolAttribute{
							Description:         "Enable advanced metadata search.",
							MarkdownDescription: "Enable advanced metadata search.",
							Computed:            true,
						},
						"advanced_metadata_search_target_name": schema.StringAttribute{
							Description:         "Advanced metadata search target name.",
							MarkdownDescription: "Advanced metadata search target name.",
							Computed:            true,
						},
						"advanced_metadata_search_target_stream": schema.StringAttribute{
							Description:         "Advanced metadata search target stream.",
							MarkdownDescription: "Advanced metadata search target stream.",
							Computed:            true,
						},
						"local_object_metadata_reads": schema.BoolAttribute{
							Description:         "Local object metadata reads bucket flag.",
							MarkdownDescription: "Local object metadata reads bucket flag.",
							Computed:            true,
						},
						"versioning_status": schema.StringAttribute{
							Description:         "Bucket versioning status.",
							MarkdownDescription: "Bucket versioning status.",
							Computed:            true,
						},
						"tag": schema.ListNestedAttribute{
							Description:         "Keywords and labels that can be added by a user to a resource to make it easy to find when doing a search.",
							MarkdownDescription: "Keywords and labels that can be added by a user to a resource to make it easy to find when doing a search.",
							Computed:            true,
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"key": schema.StringAttribute{
										Description:         "Tag key.",
										MarkdownDescription: "Tag key.",
										Computed:            true,
									},
									"value": schema.StringAttribute{
										Description:         "Tag value.",
										MarkdownDescription: "Tag value.",
										Computed:            true,
									},
								},
							},
						},
						"search_metadata": schema.SingleNestedAttribute{
							Description:         "Search metadata for the bucket.",
							MarkdownDescription: "Search metadata for the bucket.",
							Computed:            true,
							Attributes: map[string]schema.Attribute{
								"metadata": schema.ListNestedAttribute{
									Description:         "Metadata keys associated with the bucket.",
									MarkdownDescription: "Metadata keys associated with the bucket.",
									Computed:            true,
									NestedObject: schema.NestedAttributeObject{
										Attributes: map[string]schema.Attribute{
											"type": schema.StringAttribute{
												Description:         "The meta key type.",
												MarkdownDescription: "The meta key type.",
												Computed:            true,
											},
											"name": schema.StringAttribute{
												Description:         "The meta key name.",
												MarkdownDescription: "The meta key name.",
												Computed:            true,
											},
											"datatype": schema.StringAttribute{
												Description:         "The meta key data type.",
												MarkdownDescription: "The meta key data type.",
												Computed:            true,
											},
										},
									},
								},
								"is_enabled": schema.BoolAttribute{
									Description:         "Getter for the enabled flag.",
									MarkdownDescription: "Getter for the enabled flag.",
									Computed:            true,
								},
								"md_tokens": schema.BoolAttribute{
									Description:         "Getter for the mdTokens flag.",
									MarkdownDescription: "Getter for the mdTokens flag.",
									Computed:            true,
								},
								"max_keys": schema.Int64Attribute{
									Description:         "Getter for maxKeys.",
									MarkdownDescription: "Getter for maxKeys.",
									Computed:            true,
								},
							},
						},
						"min_max_governor": schema.SingleNestedAttribute{
							Description:         "Min/max governor for the bucket.",
							MarkdownDescription: "Min/max governor for the bucket.",
							Computed:            true,
							Attributes: map[string]schema.Attribute{
								"enforce_retention": schema.BoolAttribute{
									Description:         "Enforce retention flag.",
									MarkdownDescription: "Enforce retention flag.",
									Computed:            true,
								},
								"minimum_fixed_retention": schema.Int64Attribute{
									Description:         "Minimum fixed retention.",
									MarkdownDescription: "Minimum fixed retention.",
									Computed:            true,
								},
								"maximum_fixed_retention": schema.Int64Attribute{
									Description:         "Maximum fixed retention.",
									MarkdownDescription: "Maximum fixed retention.",
									Computed:            true,
								},
								"minimum_variable_retention": schema.Int64Attribute{
									Description:         "Minimum variable retention.",
									MarkdownDescription: "Minimum variable retention.",
									Computed:            true,
								},
								"maximum_variable_retention": schema.Int64Attribute{
									Description:         "Maximum variable retention.",
									MarkdownDescription: "Maximum variable retention.",
									Computed:            true,
								},
							},
						},
					},
				},
			},
		},
	}
}

// Configure loads the API client.
func (d *BucketDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	d.client = client
}

func (d *BucketDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	tflog.Trace(ctx, "BucketDataSource.Read: start")

	var data models.BucketDatasourceModel

	// Load config
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	ns := data.Namespace.ValueString()
	prefix := ""
	if !data.BucketNamePrefix.IsNull() {
		prefix = data.BucketNamePrefix.ValueString()
	}

	// Call the API to get buckets with pagination
	var allBuckets []clientgen.BucketServiceGetBucketsResponseObjectBucketInner
	var nextMarker *string
	for {
		apiReq := d.client.GenClient.BucketApi.BucketServiceGetBuckets(ctx).Namespace(ns)
		if prefix != "" {
			apiReq = apiReq.Name(prefix + "*")
		}
		if nextMarker != nil && *nextMarker != "" {
			apiReq = apiReq.Marker(*nextMarker)
		}
		apiResp, httpResp, err := apiReq.Execute()
		if err != nil {
			resp.Diagnostics.AddError(
				"Unable to read buckets",
				fmt.Sprintf("Error: %s", err),
			)
			return
		}
		if httpResp != nil && httpResp.StatusCode >= 400 {
			resp.Diagnostics.AddError(
				"API returned error",
				fmt.Sprintf("Status: %d", httpResp.StatusCode),
			)
			return
		}
		if apiResp.ObjectBucket != nil {
			allBuckets = append(allBuckets, apiResp.ObjectBucket...)
		}

		// If a name prefix was provided and no buckets were found, return an error
		if prefix != "" && len(apiResp.ObjectBucket) == 0 {
			resp.Diagnostics.AddError(
				"No buckets found with the specified prefix",
				fmt.Sprintf("No buckets found in namespace '%s' with prefix '%s'. Please check the prefix.", ns, prefix),
			)
			return
		}
		nextMarker = apiResp.NextMarker
		if nextMarker == nil || *nextMarker == "" {
			break
		}
	}

	var buckets []models.BucketModel
	for _, b := range allBuckets {
		buckets = append(buckets, mapBucketToModel(b))
	}

	data.ID = types.StringValue("buckets_" + ns)
	data.Buckets = buckets

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
	tflog.Trace(ctx, "BucketDataSource.Read: completed")
}

// mapBucketToModel maps a BucketServiceGetBucketsResponseObjectBucketInner to models.BucketModel.
func mapBucketToModel(b clientgen.BucketServiceGetBucketsResponseObjectBucketInner) models.BucketModel {
	m := models.BucketModel{
		Name:                               helper.TfString(b.Name),
		Id:                                 helper.TfString(b.Id),
		Created:                            helper.TfString(b.Created),
		Softquota:                          helper.TfString(b.Softquota),
		FsAccessEnabled:                    helper.TfBool(b.FsAccessEnabled),
		Locked:                             helper.TfBool(b.Locked),
		Vpool:                              helper.TfString(b.Vpool),
		Namespace:                          helper.TfString(b.Namespace),
		Owner:                              helper.TfString(b.Owner),
		IsStaleAllowed:                     helper.TfBool(b.IsStaleAllowed),
		IsObjectLockWithAdoAllowed:         helper.TfBool(b.IsObjectLockWithAdoAllowed),
		IsTsoReadOnly:                      helper.TfBool(b.IsTsoReadOnly),
		IsObjectLockEnabled:                helper.TfBool(b.IsObjectLockEnabled),
		DefaultObjectLockRetentionMode:     helper.TfString(b.DefaultObjectLockRetentionMode),
		DefaultObjectLockRetentionYears:    helper.TfInt64From32(b.DefaultObjectLockRetentionYears),
		DefaultObjectLockRetentionDays:     helper.TfInt64From32(b.DefaultObjectLockRetentionDays),
		IsEncryptionEnabled:                helper.TfString(b.IsEncryptionEnabled),
		DefaultRetention:                   helper.TfInt64(b.DefaultRetention),
		BlockSize:                          helper.TfInt64(b.BlockSize),
		AutoCommitPeriod:                   helper.TfInt64(b.AutoCommitPeriod),
		NotificationSize:                   helper.TfInt64(b.NotificationSize),
		ApiType:                            helper.TfString(b.ApiType),
		Retention:                          helper.TfInt64(b.Retention),
		DefaultGroupFileReadPermission:     helper.TfBool(b.DefaultGroupFileReadPermission),
		DefaultGroupFileWritePermission:    helper.TfBool(b.DefaultGroupFileWritePermission),
		DefaultGroupFileExecutePermission:  helper.TfBool(b.DefaultGroupFileExecutePermission),
		DefaultGroupDirReadPermission:      helper.TfBool(b.DefaultGroupDirReadPermission),
		DefaultGroupDirWritePermission:     helper.TfBool(b.DefaultGroupDirWritePermission),
		DefaultGroupDirExecutePermission:   helper.TfBool(b.DefaultGroupDirExecutePermission),
		DefaultGroup:                       helper.TfString(b.DefaultGroup),
		AuditDeleteExpiration:              helper.TfInt64(b.AuditDeleteExpiration),
		IsEmptyBucketInProgress:            helper.TfBool(b.IsEmptyBucketInProgress),
		BlockSizeInCount:                   helper.TfInt64(b.BlockSizeInCount),
		NotificationSizeInCount:            helper.TfInt64(b.NotificationSizeInCount),
		EnableAdvancedMetadataSearch:       helper.TfBool(b.EnableAdvancedMetadataSearch),
		AdvancedMetadataSearchTargetName:   helper.TfString(b.AdvancedMetadataSearchTargetName),
		AdvancedMetadataSearchTargetStream: helper.TfString(b.AdvancedMetadataSearchTargetStream),
		LocalObjectMetadataReads:           helper.TfBool(b.LocalObjectMetadataReads),
		VersioningStatus:                   helper.TfString(b.VersioningStatus),
	}

	// Tags
	for _, t := range b.Tag {
		m.Tag = append(m.Tag, models.TagModel{
			Key:   helper.TfString(t.Key),
			Value: helper.TfString(t.Value),
		})
	}

	// SearchMetadata
	if b.SearchMetadata != nil {
		sm := &models.SearchMetadataModel{
			IsEnabled: helper.TfBool(b.SearchMetadata.IsEnabled),
			MdTokens:  helper.TfBool(b.SearchMetadata.MdTokens),
			MaxKeys:   helper.TfInt64From32(b.SearchMetadata.MaxKeys),
		}
		for _, md := range b.SearchMetadata.Metadata {
			sm.Metadata = append(sm.Metadata, models.MetadataModel{
				Type:     helper.TfString(md.Type),
				Name:     helper.TfString(md.Name),
				Datatype: helper.TfString(md.Datatype),
			})
		}
		m.SearchMetadata = sm
	}

	// MinMaxGovernor
	if b.MinMaxGovernor != nil {
		m.MinMaxGovernor = &models.MinMaxGovernorModel{
			EnforceRetention:         helper.TfBool(b.MinMaxGovernor.EnforceRetention),
			MinimumFixedRetention:    helper.TfInt64(b.MinMaxGovernor.MinimumFixedRetention),
			MaximumFixedRetention:    helper.TfInt64(b.MinMaxGovernor.MaximumFixedRetention),
			MinimumVariableRetention: helper.TfInt64(b.MinMaxGovernor.MinimumVariableRetention),
			MaximumVariableRetention: helper.TfInt64(b.MinMaxGovernor.MaximumVariableRetention),
		}
	}

	return m
}
