/*
Copyright (c) 2025 Dell Inc., or its subsidiaries. All Rights Reserved.

Licensed under the Mozilla Public License Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://mozilla.org/MPL/2.0/


Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package provider

import (
	"context"
	"fmt"
	"strings"
	"terraform-provider-objectscale/internal/client"
	"terraform-provider-objectscale/internal/clientgen"
	"terraform-provider-objectscale/internal/helper"
	"terraform-provider-objectscale/internal/models"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listdefault"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &IAMUserResource{}
var _ resource.ResourceWithImportState = &IAMUserResource{}

func NewIAMUserResource() resource.Resource {
	return &IAMUserResource{}
}

// IAMUserResource defines the resource implementation.
type IAMUserResource struct {
	client *client.Client
}

func (r *IAMUserResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_iam_user"
}

func (r *IAMUserResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: "ObjectScale supports creation and management of IAM Users within a namespace.",
		Description:         "ObjectScale supports creation and management of IAM Users within a namespace.",
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				Description:         "Name of the user. Required.",
				MarkdownDescription: "Name of the user. Required.",
				Required:            true,
			},
			"id": schema.StringAttribute{
				Description:         "Identifier that is generated by ObjectScale when the resource is created.",
				MarkdownDescription: "Identifier that is generated by ObjectScale when the resource is created.",
				Computed:            true,
			},
			"arn": schema.StringAttribute{
				Description:         "Arn of the user.",
				MarkdownDescription: "Arn of the user.",
				Computed:            true,
			},
			"namespace": schema.StringAttribute{
				Description:         "Namespace to which the user belongs to.",
				MarkdownDescription: "Namespace to which the user belongs to.",
				Required:            true,
			},
			"create_date": schema.StringAttribute{
				Description:         "Date of creation of the IAM user",
				MarkdownDescription: "Date of creation of the IAM user",
				Computed:            true,
			},
			"path": schema.StringAttribute{
				Description:         "Path of the IAM user.",
				MarkdownDescription: "Path of the IAM user.",
				Computed:            true,
			},
			"permissions_boundary_arn": schema.StringAttribute{
				Description:         "Arn of the permissions boundary.",
				MarkdownDescription: "Arn of the permissions boundary.",
				Optional:            true,
				Computed:            true,
			},
			"permissions_boundary_type": schema.StringAttribute{
				Description:         "Type of the permissions boundary.",
				MarkdownDescription: "Type of the permissions boundary.",
				Computed:            true,
			},
			"tags": schema.ListNestedAttribute{
				Description:         "Tags associated to the user. Default: []. Updatable.",
				MarkdownDescription: "Tags associated to the user. Default: []. Updatable.",
				Optional:            true,
				Computed:            true,
				Default: listdefault.StaticValue(types.ListValueMust(types.ObjectType{AttrTypes: map[string]attr.Type{
					"key":   types.StringType,
					"value": types.StringType,
				}}, []attr.Value{})),
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"key": schema.StringAttribute{
							Description:         "Key of the tag associated to the user.",
							MarkdownDescription: "Key of the tag associated to the user.",
							Optional:            true,
							Computed:            true,
						},
						"value": schema.StringAttribute{
							Description:         "Value of the tag associated to the user.",
							MarkdownDescription: "Value of the tag associated to the user.",
							Optional:            true,
							Computed:            true,
						},
					},
				},
			},
		},
	}
}

func (r *IAMUserResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*client.Client)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

// func (r *IAMUserResource) userMappingJson(u models.NsResUserMapping) clientgen.NamespaceServiceGetNamespacesResponseNamespaceInnerUserMappingInner {
// 	return clientgen.NamespaceServiceGetNamespacesResponseNamespaceInnerUserMappingInner{
// 		Domain:    u.Domain.ValueString(),
// 		Attribute: helper.ValueListTransform(u.Attributes, r.userMappingAttrJson),
// 		Group:     helper.ValueToList[string](u.Groups),
// 	}
// }

// func (r *IAMUserResource) userMappingAttrJson(a models.NsResUserMappingAttr) clientgen.NamespaceServiceGetNamespacesResponseNamespaceInnerUserMappingInnerAttributeInner {
// 	return clientgen.NamespaceServiceGetNamespacesResponseNamespaceInnerUserMappingInnerAttributeInner{
// 		Key:   a.Key.ValueString(),
// 		Value: helper.ValueToList[string](a.Value),
// 	}
// }

func (r *IAMUserResource) modelToJson(plan models.IAMUserResourceModel) clientgen.IamServiceCreateUserResponseCreateUserResultUser {
	return clientgen.IamServiceCreateUserResponseCreateUserResultUser{
		UserName:   helper.ValueToPointer[string](plan.Name),
		UserId:     helper.ValueToPointer[string](plan.Id),
		Arn:        helper.ValueToPointer[string](plan.Arn),
		CreateDate: helper.ValueToPointer[string](plan.CreateDate),
		Path:       helper.ValueToPointer[string](plan.Path),
		// PermissionsBoundaryArn:  helper.ValueToPointer[string](plan.PermissionsBoundaryArn),
		// PermissionsBoundaryType: helper.ValueToPointer[string](plan.PermissionsBoundaryType),
	}
}

func (r *IAMUserResource) tagJson(a models.Tags) clientgen.IamServiceCreateUserResponseCreateUserResultUserTagsInner {
	return clientgen.IamServiceCreateUserResponseCreateUserResultUserTagsInner{
		Key:   a.Key.ValueString(),
		Value: a.Value.ValueString(),
	}
}

func (r *IAMUserResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	tflog.Info(ctx, "creating user")
	var plan models.IAMUserResourceModel

	// Read Terraform plan data into the model
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)

	if resp.Diagnostics.HasError() {
		return
	}

	tags := helper.ValueListTransform(plan.Tags, r.tagJson) // returns []clientgen.IamServiceCreateUserResponseCreateUserResultUserTagsInner
	var tagsMap []map[string]interface{}
	for _, t := range tags {
		tagsMap = append(tagsMap, map[string]interface{}{
			"key":   t.Key,
			"value": t.Value,
		})
	}

	_, _, err := r.client.GenClient.IamApi.IamServiceCreateUser(ctx).UserName(plan.Name.ValueString()).XEmcNamespace(plan.Namespace.ValueString()).PermissionsBoundary(plan.PermissionsBoundaryArn.ValueString()).TagsMemberN(tagsMap).Execute()
	if err != nil {
		resp.Diagnostics.AddError("Error creating user", err.Error())
		return
	}

	iam_user, _, err := r.client.GenClient.IamApi.IamServiceGetUser(ctx).UserName(plan.Name.ValueString()).XEmcNamespace(plan.Namespace.ValueString()).Execute()
	// data := r.getModel(iam_user)
	data := r.getModel(&clientgen.IamServiceCreateUserResponseCreateUserResultUser{
		UserId:              iam_user.GetUserResult.User.UserId,
		UserName:            iam_user.GetUserResult.User.UserName,
		Arn:                 iam_user.GetUserResult.User.Arn,
		CreateDate:          iam_user.GetUserResult.User.CreateDate,
		Path:                iam_user.GetUserResult.User.Path,
		PermissionsBoundary: iam_user.GetUserResult.User.PermissionsBoundary,
		Tags:                iam_user.GetUserResult.User.Tags,
	}, plan.Namespace)

	// Save data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *IAMUserResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	tflog.Info(ctx, "reading user")
	var state models.IAMUserResourceModel

	// Read Terraform prior state data into the model
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)

	if resp.Diagnostics.HasError() {
		return
	}

	iam_user, _, err := r.client.GenClient.IamApi.IamServiceGetUser(ctx).UserName(state.Name.ValueString()).XEmcNamespace(state.Namespace.ValueString()).Execute()

	if err != nil {
		resp.Diagnostics.AddError("Error reading user", err.Error())
		return
	}

	// data := r.getModel(iam_user)
	data := r.getModel(&clientgen.IamServiceCreateUserResponseCreateUserResultUser{
		UserId:              iam_user.GetUserResult.User.UserId,
		UserName:            iam_user.GetUserResult.User.UserName,
		Arn:                 iam_user.GetUserResult.User.Arn,
		CreateDate:          iam_user.GetUserResult.User.CreateDate,
		Path:                iam_user.GetUserResult.User.Path,
		PermissionsBoundary: iam_user.GetUserResult.User.PermissionsBoundary,
		Tags:                iam_user.GetUserResult.User.Tags,
	}, state.Namespace)
	// Save updated plan into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *IAMUserResource) getModel(
	// iam_user *clientgen.IamServiceCreateUserResponseCreateUserResultUser,
	iam_user *clientgen.IamServiceCreateUserResponseCreateUserResultUser,
	namespace types.String) models.IAMUserResourceModel {
	var permissionsBoundaryArn, permissionsBoundaryType basetypes.StringValue

	// Check if PermissionsBoundary exists
	if iam_user.PermissionsBoundary != nil {
		permissionsBoundaryArn = helper.TfStringNN(iam_user.PermissionsBoundary.PermissionsBoundaryArn)
		permissionsBoundaryType = helper.TfStringNN(iam_user.PermissionsBoundary.PermissionsBoundaryType)
	} else {
		// Set empty values if missing
		permissionsBoundaryArn = types.StringValue("")
		permissionsBoundaryType = types.StringValue("")
	}
	return models.IAMUserResourceModel{

		Id:                      helper.TfStringNN(iam_user.UserId),
		Name:                    helper.TfStringNN(iam_user.UserName),
		Arn:                     helper.TfStringNN(iam_user.Arn),
		Namespace:               namespace,
		CreateDate:              helper.TfStringNN(iam_user.CreateDate),
		Path:                    helper.TfStringNN(iam_user.Path),
		PermissionsBoundaryType: permissionsBoundaryType,
		PermissionsBoundaryArn:  permissionsBoundaryArn,
		Tags: helper.ListNotNull(iam_user.Tags,
			func(v *clientgen.IamServiceCreateUserResponseCreateUserResultUserTagsInner) types.Object {
				if v == nil {
					v = &clientgen.IamServiceCreateUserResponseCreateUserResultUserTagsInner{}
				}
				return helper.Object(models.Tags{
					Key:   types.StringValue(v.Key),
					Value: types.StringValue(v.Value),
				})
			}),
	}
}

// // computes the difference between two string sets (lists)
// func (r *IAMUserResource) vpoolDiff(first, second []string) []string {
// 	var diff []string
// 	smap := make(map[string]struct{}, len(second))
// 	for _, v := range second {
// 		smap[v] = struct{}{}
// 	}
// 	for _, v := range first {
// 		if _, ok := smap[v]; !ok {
// 			diff = append(diff, v)
// 		}
// 	}
// 	return diff
// }

// func (r *IAMUserResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {

// 	// resp.Diagnostics.AddError("[Update] Update operation is not available.", "Update operation is not available.")
// 	tflog.Info(ctx, "updating user")
// 	// TODO: Add update logic
// 	var plan, state models.IAMUserResourceModel

// 	// Read Terraform plan and state data into the models
// 	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
// 	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
// 	if resp.Diagnostics.HasError() {
// 		return
// 	}

// 	// To prevent the non-updatable fields from being changed
// 	if !plan.Name.Equal(state.Name) {
// 		resp.Diagnostics.AddError("Error updating user", "Fields of `name`, `arn` and `create_date` are not updatable")
// 		return
// 	}

// 	// planJson, stateJson := r.modelToJson(plan), r.modelToJson(state)

// 	// ureq := r.client.GenClient.NamespaceApi.NamespaceServiceUpdateNamespace(ctx, state.Id.ValueString())
// 	_, _, err := r.client.GenClient.IamApi.IamServicePutUserPermissionsBoundary(ctx).UserName(plan.Name.ValueString()).XEmcNamespace(plan.Namespace.ValueString()).PermissionsBoundary(plan.PermissionsBoundaryArn.ValueString()).Execute()
// 	if err != nil {
// 		resp.Diagnostics.AddError("Error updating the permission boundary of the user", err.Error())
// 		return
// 	}

// 	iam_user, _, err := r.client.GenClient.IamApi.IamServiceGetUser(ctx).UserName(state.Name.ValueString()).XEmcNamespace(state.Namespace.ValueString()).Execute()

// 	if err != nil {
// 		resp.Diagnostics.AddError("Error reading user", err.Error())
// 		return
// 	}

// 	data := r.getModel(&clientgen.IamServiceCreateUserResponseCreateUserResultUser{
// 		UserId:              iam_user.GetUserResult.User.UserId,
// 		UserName:            iam_user.GetUserResult.User.UserName,
// 		Arn:                 iam_user.GetUserResult.User.Arn,
// 		CreateDate:          iam_user.GetUserResult.User.CreateDate,
// 		Path:                iam_user.GetUserResult.User.Path,
// 		PermissionsBoundary: iam_user.GetUserResult.User.PermissionsBoundary,
// 		Tags:                iam_user.GetUserResult.User.Tags,
// 	}, state.Namespace)
// 	// Save updated plan into Terraform state
// 	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)

// }
func strPtr(s string) *string {
	return &s
}

func (r *IAMUserResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	tflog.Info(ctx, "updating user")

	var plan, state models.IAMUserResourceModel

	// Read Terraform plan and state data
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Prevent non-updatable fields from being changed
	if !plan.Name.Equal(state.Name) {
		resp.Diagnostics.AddError("Error updating user", "Fields `name`, `arn`, and `create_date` are not updatable")
		return
	}

	// // Compare Tags: plan.Tags (B) vs state.Tags (A)
	// inPlanNotState, inStateNotPlan := compareTags(plan.Tags, state.Tags)

	// tflog.Debug(ctx, fmt.Sprintf("Tags to add/update: %v", inPlanNotState))
	// tflog.Debug(ctx, fmt.Sprintf("Tags to remove: %v", inStateNotPlan))

	// // Example: Apply tag changes via API (pseudo-code)
	// if len(inPlanNotState) > 0 {
	//     // Call API to add/update tags
	//     _, _, err := r.client.GenClient.IamApi.IamServiceTagUser(ctx).
	//         UserName(plan.Name.ValueString()).
	//         XEmcNamespace(plan.Namespace.ValueString()).
	//         TagsMemberN(inPlanNotState).
	//         Execute()
	//     if err != nil {
	//         resp.Diagnostics.AddError("Error adding/updating tags", err.Error())
	//         return
	//     }
	// }

	// if len(inStateNotPlan) > 0 {
	//     // Call API to remove tags
	//     // _, _, err := r.client.GenClient.IamApi.IamServiceUntagUser(ctx).
	//     //     UserName(plan.Name.ValueString()).
	//     //     XEmcNamespace(plan.Namespace.ValueString()).
	//     //     TagKeys(extractKeys(inStateNotPlan)).
	//     //     Execute()
	//     // if err != nil {
	//     //     resp.Diagnostics.AddError("Error removing tags", err.Error())
	//     //     return
	//     // }

	// 	keys := extractKeys(inStateNotPlan)
	// 	var tagKeysParam []clientgen.IamServiceUntagUserTagKeysParameter
	// 	for _, k := range keys {
	// 		tagKeysParam = append(tagKeysParam, clientgen.IamServiceUntagUserTagKeysParameter(k))
	// 	}

	// 	_, _, err := r.client.GenClient.IamApi.IamServiceUntagUser(ctx).
	// 		UserName(plan.Name.ValueString()).
	// 		XEmcNamespace(plan.Namespace.ValueString()).
	// 		TagKeys(tagKeysParam).
	// 		Execute()
	// 	if err != nil {
	//         resp.Diagnostics.AddError("Error removing tags", err.Error())
	//         return
	// 	}
	// }
	tags_plan := helper.ValueListTransform(plan.Tags, r.tagJson) // returns []clientgen.IamServiceCreateUserResponseCreateUserResultUserTagsInner
	var tagsMap_plan []map[string]interface{}
	for _, t := range tags_plan {
		tagsMap_plan = append(tagsMap_plan, map[string]interface{}{
			"key":   t.Key,
			"value": t.Value,
		})
	}

	tags_state := helper.ValueListTransform(state.Tags, r.tagJson) // returns []clientgen.IamServiceCreateUserResponseCreateUserResultUserTagsInner
	var tagsMap_state []map[string]interface{}
	var tag_state_keys []clientgen.IamServiceUntagUserTagKeysParameterKeysInner
	for _, t := range tags_state {
		tagsMap_state = append(tagsMap_state, map[string]interface{}{
			"key":   t.Key,
			"value": t.Value,
		})
		tag_state_keys = append(tag_state_keys, clientgen.IamServiceUntagUserTagKeysParameterKeysInner{
			Key: strPtr(t.Key),
		})
	}

	// var untagKeysParam clientgen.IamServiceUntagUserTagKeysParameter
	// untagKeysParam = clientgen.IamServiceUntagUserTagKeysParameter{Keys: tag_state_keys}

	// _, _, err_untag := r.client.GenClient.IamApi.IamServiceUntagUser(ctx).
	// 	UserName(plan.Name.ValueString()).
	// 	XEmcNamespace(plan.Namespace.ValueString()).
	// 	TagKeys(untagKeysParam).
	// 	Execute()
	// if err_untag != nil {
	// 	resp.Diagnostics.AddError("Error removing tags", err_untag.Error())
	// 	return
	// }

	_, _, err_tag := r.client.GenClient.IamApi.IamServiceTagUser(ctx).
		UserName(plan.Name.ValueString()).
		XEmcNamespace(plan.Namespace.ValueString()).
		TagsMemberN(tagsMap_plan).
		Execute()
	if err_tag != nil {
		resp.Diagnostics.AddError("Error removing tags", err_tag.Error())
		return
	}
	// Update permission boundary
	_, _, err := r.client.GenClient.IamApi.IamServicePutUserPermissionsBoundary(ctx).
		UserName(plan.Name.ValueString()).
		XEmcNamespace(plan.Namespace.ValueString()).
		PermissionsBoundary(plan.PermissionsBoundaryArn.ValueString()).
		Execute()
	if err != nil {
		resp.Diagnostics.AddError("Error updating permission boundary", err.Error())
		return
	}

	// Refresh user data
	iam_user, _, err := r.client.GenClient.IamApi.IamServiceGetUser(ctx).
		UserName(state.Name.ValueString()).
		XEmcNamespace(state.Namespace.ValueString()).
		Execute()
	if err != nil {
		resp.Diagnostics.AddError("Error reading user", err.Error())
		return
	}

	data := r.getModel(&clientgen.IamServiceCreateUserResponseCreateUserResultUser{
		UserId:              iam_user.GetUserResult.User.UserId,
		UserName:            iam_user.GetUserResult.User.UserName,
		Arn:                 iam_user.GetUserResult.User.Arn,
		CreateDate:          iam_user.GetUserResult.User.CreateDate,
		Path:                iam_user.GetUserResult.User.Path,
		PermissionsBoundary: iam_user.GetUserResult.User.PermissionsBoundary,
		Tags:                iam_user.GetUserResult.User.Tags,
	}, state.Namespace)

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// // Helper: Compare Tags
// func compareTags(listB, listA []models.Tags) ([]models.Tags, []models.Tags) {
//     mapA := make(map[string]string)
//     mapB := make(map[string]string)

//     for _, t := range listA {
//         mapA[t.Key] = t.Value
//     }
//     for _, t := range listB {
//         mapB[t.Key] = t.Value
//     }

//     var inBNotA []models.Tag
//     for _, t := range listB {
//         if val, exists := mapA[t.Key]; !exists || val != t.Value {
//             inBNotA = append(inBNotA, t)
//         }
//     }

//     var inANotB []models.Tag
//     for _, t := range listA {
//         if val, exists := mapB[t.Key]; !exists || val != t.Value {
//             inANotB = append(inANotB, t)
//         }
//     }

//     return inBNotA, inANotB
// }

// // Helper: Extract keys for untagging
// func extractKeys(tags []models.Tag) []string {
//     keys := make([]string, len(tags))
//     for i, t := range tags {
//         keys[i] = t.Key
//     }
//     return keys
// }

func (r *IAMUserResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	tflog.Info(ctx, "deleting IAM user")
	var state models.IAMUserResourceModel

	// Read Terraform prior state data into the model
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)

	if resp.Diagnostics.HasError() {
		return
	}

	_, _, err := r.client.GenClient.IamApi.IamServiceDeleteUser(ctx).UserName(state.Name.ValueString()).XEmcNamespace(state.Namespace.ValueString()).Execute()

	if err != nil {
		resp.Diagnostics.AddError(
			"Error deleting IAM user",
			err.Error(),
		)
	}
}

func (r *IAMUserResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	tflog.Info(ctx, "importing IAM user")

	parts := strings.SplitN(req.ID, ":", 2)
	if len(parts) != 2 {
		resp.Diagnostics.AddError("Error importing IAM user", "invalid format: expected 'username:namespace'")
	}
	username := parts[0]
	namespace := parts[1]

	iam_user, _, err := r.client.GenClient.IamApi.IamServiceGetUser(ctx).UserName(username).XEmcNamespace(namespace).Execute()

	if err != nil {
		resp.Diagnostics.AddError("Error reading user", err.Error())
		return
	}

	// data := r.getModel(iam_user)
	data := r.getModel(&clientgen.IamServiceCreateUserResponseCreateUserResultUser{
		UserId:              iam_user.GetUserResult.User.UserId,
		UserName:            iam_user.GetUserResult.User.UserName,
		Arn:                 iam_user.GetUserResult.User.Arn,
		CreateDate:          iam_user.GetUserResult.User.CreateDate,
		Path:                iam_user.GetUserResult.User.Path,
		PermissionsBoundary: iam_user.GetUserResult.User.PermissionsBoundary,
		Tags:                iam_user.GetUserResult.User.Tags,
	}, types.StringValue(namespace))
	// Save updated plan into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
	// resp.Diagnostics.AddError("[Import] Import operation is not available.", "Import operation is not available.")

}
